#!/usr/bin/env ruby

begin
  require 'pipin'
rescue LoadError # for development
  $LOAD_PATH.unshift File.dirname(File.expand_path(__FILE__)) + '/../lib'
  require 'pipin'
end

case ARGV.shift
when '--version', '-v'
  puts "Pipin #{Pipin::VERSION}"
when 'new', 'n'
  dir = ARGV.shift || raise("Options should be given after the application name")
  Pipin::Exec.new(dir).create_from_template
else
  puts <<__USAGE__
Usage:
  rails new BLOG_PATH [options]
 
Options:

Pipin options:
  -v, [--version]  # Show Pipin version number and quit

Example:
    rails new ~/myblog

    Create a new pipin blog. "pipin new ~/myblog" creates a
    new blog files in "~/myblog".
__USAGE__
end
