#!/usr/bin/env ruby

begin
  require 'pipin'
rescue LoadError # for development
  $LOAD_PATH.unshift File.dirname(File.expand_path(__FILE__)) + '/../lib'
  require 'pipin'
end

case ARGV.shift
when 'new'
  dir = ARGV.shift || raise("Options should be given after the application name")
  Pipin::Exec.new(dir).create_from_template
else
puts <<__USAGE__
Usage: pipin COMMAND [ARGS]

The most common pipin commands are:
 new         Create a new pipin blog. "pipin new my_blog_dir" creates a
             new blog files in "./my_blog_dir"
__USAGE__
end
